# Site settings
title: Christopher Kuzma
description: Personal website of Christopher Kuzma
username: Christopher Kuzma
user_title: Computational Linguist
email: chris.kuzma@gmail.com
cv: /assets/data/kuzma_resume_web.pdf
linkedin: chriskuzma
blog: https://github.com/ckuzma/blog
github_username:  ckuzma

exclude: ['package.json', 'src' , 'node_modules']
